### ISSUE TITLE
有关PAL的问题

### ISSUE THREAD

**Issue by WuTUT** [ppx123-web/ICS2020#1]
您好，
请问我从网络下载的PAL（仙剑98版）即便删除掉AVI文件也会超过ramdisk要求的48MB，应该如何继续裁剪？
另外，/share/games/pal/sdlpal.cfg文件内容应该如何配置？
我可以用SDL-PAL来运行PAL，但是同样的这份游戏数据在Nano-lite上却不断提示缺少各种文件。

非常感谢！

**Comment by ppx123-web** [comment]
[sdlpal-master.zip](https://github.com/ppx123-web/ICS2020/files/5926162/sdlpal-master.zip)
这个是配置文件，如何使用可以在https://nju-projectn.github.io/ics-pa-gitbook/ics2020/3.5.html#pal-%E4%BB%99%E5%89%91%E5%A5%87%E4%BE%A0%E4%BC%A0网页中找到说明。
关于PAL过大的问题，这个问题我没有遇到过，不过可以尝试从我上传的文件直接下载，里面也包括了配置文件，应该不会超过48MB

**Comment by WuTUT** [comment]
非常感谢您的回复，但是我更困惑了...我的SDL-PAL和您一样。
我的仙剑是Pal98rqp，即便去掉4个视频也有50M，我怀疑我的仙剑版本并不是PA教程提到的那一款（95/DOS/98）？

> total 237M
> -rw-rw-r-- 1 wu wu 173K 9月   2  1997 0.rpg
> -rw-rw-r-- 1 wu wu 8.7M 3月  31  2051 1.AVI
> -rw-rw-r-- 1 wu wu  31M 3月  31  2051 2.AVI
> -rw-rw-r-- 1 wu wu  20M 3月  31  2051 3.AVI
> -rw-rw-r-- 1 wu wu 7.5M 3月  31  2051 4.AVI
> -rw-rw-r-- 1 wu wu  79M 3月  31  2051 5.AVI
> -rw-rw-r-- 1 wu wu  36M 3月  31  2051 6.AVI
> -rw-rw-r-- 1 wu wu 911K 1月   8  1998 Abc.mkf
> -rw-rw-r-- 1 wu wu 142K 1月   8  1998 Ball.mkf
> -rw-rw-r-- 1 wu wu  63K 1月   8  1998 Data.mkf
> -rw-rw-r-- 1 wu wu 1.2M 1月   8  1998 Fbp.mkf
> -rw-rw-r-- 1 wu wu 747K 1月   8  1998 Fire.mkf
> -rw-rw-r-- 1 wu wu 170K 1月   8  1998 F.mkf
> -rw-rw-r-- 1 wu wu  16M 1月   8  1998 Gop.mkf
> drwxrwxr-x 3 wu wu 4.0K 6月  12  2008 HomePage.PAL
> -rw-rw-r-- 1 wu wu 2.7K 1月   8  1998 Logo.ico
> -rw-rw-r-- 1 wu wu 1.6M 2月   2  2008 Map.mkf
> -rw-rw-r-- 1 wu wu 1.4M 1月   8  1998 Mgo.mkf
> -rw-rw-r-- 1 wu wu 220K 7月  26  2008 M.msg
> drwxrwxr-x 2 wu wu 4.0K 6月  16  2008 Musics
> -rw-rw-r-- 1 wu wu 324K 7月  25  1995 MUS.MKF
> -rw-rw-r-- 1 wu wu  755 6月  18  2008 PAL.Administrator.ini
> -rw-rw-r-- 1 wu wu 424K 6月  17  2008 Pal.dll
> -rw-rw-r-- 1 wu wu 166K 10月  6  2007 Pal.exe
> -rw-rw-r-- 1 wu wu  63K 8月   4  2007 PALOLD.DLL
> -rw-rw-r-- 1 wu wu 8.3K 1月   8  1998 Pat.mkf
> -rw-rw-r-- 1 wu wu 443K 1月   8  1998 Rgm.mkf
> -rw-rw-r-- 1 wu wu 3.9M 1月   8  1998 Rng.mkf
> -rwxrwxr-x 1 wu wu  11M 2月   4 20:10 sdlpal
> -rw-rw-r-- 1 wu wu  18M 1月   8  1998 Sounds.mkf
> -rw-rw-r-- 1 wu wu 562K 7月  22  2008 Sss.mkf
> -rw-rw-r-- 1 wu wu 705K 1月   8  1998 Vb40032.dll
> -rw-rw-r-- 1 wu wu 5.6K 1月   8  1998 Word.dat

在运行时
[/home/wu/Documents/code/nju_pa/ics2020/nanos-lite/src/syscall.c,46,do_syscall] Handle syscall(brk) ID = 9
address (0x7a65645f) is out of bound {???} [0x00000000, 0x00000000] at pc = 0x0303780a
x86-nemu-interpreter: src/device/io/map.c:21: check_bound: Assertion `map != ((void *)0) && addr <= map->high && addr >= map->low' failed.
make[1]: *** [Makefile:108: run] Aborted (core dumped)

我不太能确定是否是我的程序出现了bug，还是我的下载的仙剑版本有问题
（当我单独运行bird/nslider等程序时正确，但仅仅是将仙剑文件加入不运行仙剑时就会发生几次brk后崩溃）

**Comment by WuTUT** [comment]
额，我想应该是我的问题，我已经换了更小的仙剑版本，brk一直在飞快调用

**Comment by WuTUT** [comment]
非常感谢
